# Generated by Django 3.0.2 on 2020-01-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
