# Generated by Django 3.0.2 on 2020-01-05 09:48

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200105_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='engine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
